name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Ruff Check
        run: uv run ruff check .

      - name: Ruff Format
        run: uv run ruff format --diff .
